### ISSUE TITLE
Nothing Printing

### ISSUE THREAD

**Issue by grstreten** [seven1m/dymo-printer-agent#8]
The server receives my POST requests to /DYMO/DLS/Printing/PrintLabel - in this case I'm trying to use the sample label design. Nothing is being queued to CUPS. CUPS is working perfectly fine with the printer otherwise...

Anybody encountered such an issue? Cheers.

**Comment by seven1m** [comment]
I've noticed this doesn't work on newer Raspbian because `lpr` is missing. I'm not sure yet how to install it. Follow #6 for progress.
